#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Post-train per-validator gate check from train report.")
    p.add_argument("--report-json", required=True, help="Path to report generated by train_cpu_real.py")
    p.add_argument(
        "--required-improvement",
        type=float,
        default=0.0,
        help="Required relative improvement ratio (default 0.0).",
    )
    p.add_argument("--out-json", default="", help="Optional path to write gate summary JSON.")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    report = json.loads(Path(args.report_json).read_text(encoding="utf-8"))
    before = report.get("before_by_validator_ce", {})
    after = report.get("after_by_validator_ce", {})
    if not before or not after:
        raise SystemExit("Report missing per-validator CE sections.")

    req = float(args.required_improvement)
    rows = []
    all_pass = True
    print("validator_uid,before_ce,req_ce,after_ce,margin(req-after),pass")
    for vid in sorted(before.keys(), key=lambda x: int(x)):
        b = float(before[vid])
        a = float(after.get(vid, float("nan")))
        req_ce = b * (1.0 - req)
        margin = req_ce - a
        passed = a <= req_ce
        if not passed:
            all_pass = False
        rows.append(
            {
                "validator_uid": int(vid),
                "before_ce": b,
                "required_ce": req_ce,
                "after_ce": a,
                "margin": margin,
                "pass": passed,
            }
        )
        print(
            f"{vid},{b:.6f},{req_ce:.6f},{a:.6f},{margin:.6f},{'PASS' if passed else 'FAIL'}"
        )

    summary = {
        "all_validators_pass": all_pass,
        "required_improvement": req,
        "rows": rows,
    }
    if args.out_json:
        Path(args.out_json).write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print()
    print(f"ALL_VALIDATORS_PASS={all_pass}")
    return 0 if all_pass else 2


if __name__ == "__main__":
    raise SystemExit(main())

